theme: jekyll-theme-cayman
title: [Rosalie Noel]
description: [Welcome to my Data Science projects portfolio]
<p>Connect on Linkedin: <a href="https://www.linkedin.com/in/rosalienoel/">rosalienoel</a><\p>
